# Generated by Django 6.0.4 on 2026-07-31 10:18

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionarySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year of Publication')),
                ('shortname', models.CharField(max_length=200, verbose_name='Source Short Name')),
                ('identifier', models.CharField(max_length=1000, verbose_name='Source Identifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year of Publication')),
                ('shortname', models.CharField(max_length=200, verbose_name='Source Short Name')),
                ('identifier', models.CharField(max_length=1000, verbose_name='Source Identifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Language Name')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='ISO 639-3 Code')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abb', models.CharField(max_length=50, unique=True, verbose_name='POS Abbreviation')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='POS Full Name')),
                ('description', models.TextField(verbose_name='POS Description')),
                ('sort_order', models.IntegerField(default=0, verbose_name='POS Sort Order')),
            ],
            options={
                'verbose_name_plural': 'Parts of Speech',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persoarabic', models.CharField(help_text='The headword in Perso-Arabic script. This is the primary form of the word as it appears in the dictionary.', max_length=500, verbose_name='Perso-Arabic Headword')),
                ('latin_strict', models.CharField(help_text='The verbatim Latin transliteration of the headword, strictly following user guidelines and omitting non-present short vowels.', max_length=500, verbose_name='Verbatim Latin Transliteration')),
                ('latin_strict_stripped', models.GeneratedField(db_persist=True, expression=models.Func(models.F('latin_strict'), models.Value('äöüāčīšşūźżǧʿʾḥḫṗṣṭẓ'), models.Value("aouacissuzzg''hhpstz"), function='translate'), help_text='This field is automatically generated by stripping diacritics and special characters from the verbatim Latin transliteration. It is used for search and sorting purposes.', output_field=models.CharField(max_length=500))),
                ('latin_phonetic', models.CharField(blank=True, help_text="The phonetic Latin transcription of the headword, where inputters/editors can make informed decisions about the word's pronunciation.", max_length=500, verbose_name='Phonetic Latin Transcription')),
                ('latin_phonetic_stripped', models.GeneratedField(db_persist=True, expression=models.Func(models.F('latin_phonetic'), models.Value('äöüāčīšşūźżǧʿʾḥḫṗṣṭẓ'), models.Value("aouacissuzzg''hhpstz"), function='translate'), help_text='This field is automatically generated by stripping diacritics and special characters from the phonetic Latin transcription. It is used for search and sorting purposes.', output_field=models.CharField(max_length=500))),
                ('homograph_index', models.PositiveSmallIntegerField(blank=True, help_text="Ordinal distinguishing this entry from other entries sharing the same Perso-Arabic headword but representing a distinct, etymologically unrelated word (e.g. 'ot' fire vs. 'ot' grass). Null when the headword has no homographs. Auto-assigned on creation; editable via the sortable admin widget.", null=True, verbose_name='Homograph Index')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'constraints': [models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('persoarabic', 'homograph_index'), name='unique_homograph_index')],
            },
        ),
        migrations.CreateModel(
            name='AlternateSpelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persoarabic', models.CharField(help_text='An alternative spelling of the headword in Perso-Arabic script. Words with diacritics added/missing are alternate spellings.', max_length=500, verbose_name='Alternate Spelling in Perso-Arabic')),
                ('latin_strict', models.CharField(help_text='The corresponding verbatim Latin transliteration of the alternate spelling.', max_length=500, verbose_name='Alternate Spelling in Verbatim Latin')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Etymology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Chain Order')),
                ('word', models.CharField(max_length=500, verbose_name='Source Word')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.entry')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.language')),
            ],
            options={
                'verbose_name_plural': 'Etymologies',
                'ordering': ['entry', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_text', models.TextField(verbose_name='Definition Text')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.dictionarysource')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.entry')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.partofspeech')),
            ],
        ),
        migrations.CreateModel(
            name='UsageExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persoarabic', models.TextField(verbose_name='Usage Example in Perso-Arabic')),
                ('latin_strict', models.TextField(verbose_name='Usage Example in Verbatim Latin')),
                ('gloss', models.TextField(blank=True, verbose_name='English Gloss of Usage Example')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.definition')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.genericsource')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField(verbose_name='Note Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='dictionary__content_b0dc6b_idx')],
            },
        ),
    ]
