# Generated by Django 6.0.4 on 2026-08-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternatespelling',
            name='latin_strict_stripped',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('latin_strict'), models.Value('äöüāčīšşūźżǧʿʾḥḫṗṣṭẓ'), models.Value("aouacissuzzg''hhpstz"), function='translate'), help_text='This field is automatically generated by stripping diacritics and special characters from the verbatim Latin transliteration. It is used for search and sorting purposes.', output_field=models.CharField(max_length=500)),
        ),
    ]
