# Generated by Django 6.0.4 on 2026-08-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alternatespelling_latin_strict_stripped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionarysource',
            name='identifier',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Source Identifier'),
        ),
        migrations.AlterField(
            model_name='genericsource',
            name='identifier',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Source Identifier'),
        ),
    ]
