# Generated by Django 6.0.4 on 2026-08-03 09:24
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_dictionarysource_identifier_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
