# Generated by Django 6.0.4 on 2026-08-03 09:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alternatespelling',
            index=django.contrib.postgres.indexes.GinIndex(fields=['persoarabic'], name='as_persoarabic_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='alternatespelling',
            index=django.contrib.postgres.indexes.GinIndex(fields=['latin_strict'], name='as_latin_strict_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='alternatespelling',
            index=django.contrib.postgres.indexes.GinIndex(fields=['latin_strict_stripped'], name='as_latin_strict_stripped_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['persoarabic'], name='entry_persoarabic_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['latin_strict'], name='entry_latin_strict_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['latin_strict_stripped'], name='entry_latin_strict_stripped_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['latin_phonetic'], name='entry_latin_phonetic_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['latin_phonetic_stripped'], name='entry_latin_phonetic_stripped_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
