# Generated by Django 6.0.4 on 2026-08-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alternatespelling_as_persoarabic_trgm_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alternatespelling',
            new_name='as_ls_stripped_trgm',
            old_name='as_latin_strict_stripped_trgm',
        ),
        migrations.RenameIndex(
            model_name='entry',
            new_name='entry_ls_stripped_trgm',
            old_name='entry_latin_strict_stripped_trgm',
        ),
        migrations.RenameIndex(
            model_name='entry',
            new_name='entry_lp_stripped_trgm',
            old_name='entry_latin_phonetic_stripped_trgm',
        ),
    ]
