# Generated by Django 6.0.4 on 2026-08-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_rename_as_latin_strict_stripped_trgm_as_ls_stripped_trgm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'ordering': ['entry', 'pos__sort_order', 'sequence']},
        ),
        migrations.AddField(
            model_name='definition',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
