from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models

# ---------------------------------------------------------------------------
# Controlled vocabularies
# ---------------------------------------------------------------------------

class PartOfSpeech(models.Model):
	abb = models.CharField("POS Abbreviation", max_length=50, unique=True)	# e.g. N., V., Adj.
	name = models.CharField("POS Full Name", max_length=200, unique=True)	# e.g. noun, verb, adjective
	description = models.TextField("POS Description")						# the usual, although useful for very specific Turkic grammar explanations
	sort_order = models.IntegerField("POS Sort Order", default=0)			# for ordering in the UI

	class Meta:
		ordering = ["sort_order", "name"]
		verbose_name_plural = "Parts of Speech"
	
	def __str__(self):
		return self.name

class Language(models.Model):
	name = models.CharField("Language Name", max_length=200, unique=True)			# e.g. Arabic, Old Turkic, Persian
	iso_code = models.CharField("ISO 639-3 Code", max_length=3, unique=True)		# e.g. ara, ota, pes

	class Meta:
		ordering = ["name"]

	def __str__(self):
		return self.name

# ---------------------------------------------------------------------------
# Notes - a generic entity that can be attached to multiple others
# ---------------------------------------------------------------------------

class Note(models.Model):
	content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
	object_id = models.PositiveIntegerField()
	content_object = GenericForeignKey('content_type', 'object_id')

	text = models.TextField("Note Text")
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ["created_at"]
		indexes = [models.Index(fields=['content_type', 'object_id'])]

	def __str__(self):
		return f"Note for {self.content_object} ({self.created_at})"

# ---------------------------------------------------------------------------
# Entry
# ---------------------------------------------------------------------------

class Entry(models.Model):
	persoarabic = models.CharField(
		"Perso-Arabic Headword", 
		max_length=500,
		help_text=(
			"The headword in Perso-Arabic script. "
			"This is the primary form of the word as it appears in the dictionary."
		)
	) # e.g. غنیمت
	latin_strict = models.CharField(
		"Verbatim Latin Transliteration", 
		max_length=500,
		help_text=(
			"The verbatim Latin transliteration of the headword, "
			"strictly following user guidelines and omitting non-present short vowels."
		)
	) # e.g. ġnymt
	latin_phonetic = models.CharField(
		"Phonetic Latin Transcription", 
		max_length=500,
		help_text=(
			"The phonetic Latin transcription of the headword, "
			"where inputters/editors can make informed decisions about the word's pronunciation."
		)
	) # e.g. ġanīmat

	latin_strict_stripped = models.CharField(
		"Stripped Verbatim Latin Transliteration",
		max_length=500,
		blank=True,
		editable=False,
		help_text=(
			"This field is automatically generated by stripping diacritics " 
			"and special characters from the verbatim Latin transliteration. "
			"It is used for search and sorting purposes."
		)
	) # e.g. gnymt
	latin_phonetic_stripped = models.CharField(
		"Stripped Phonetic Latin Transcription",
		max_length=500,
		blank=True,
		editable=False,
		help_text=(
			"This field is automatically generated by stripping diacritics " 
			"and special characters from the phonetic Latin transcription. "
			"It is used for search and sorting purposes."
		)
	) # e.g. ganimat

	notes = GenericRelation(Note)

	class Meta:
		verbose_name_plural = "Entries"
		

class AlternateSpelling(models.Model):
	entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
	persoarabic = models.CharField(
		"Alternate Spelling in Perso-Arabic", 
		max_length=500, 
		help_text=(
			"An alternative spelling of the headword in Perso-Arabic script. " 
			"Words with diacritics added/missing are alternate spellings."
		)
	)
	latin_strict = models.CharField(
		"Alternate Spelling in Verbatim Latin", 
		max_length=500, 
		help_text=(
			"The corresponding verbatim Latin transliteration of the alternate spelling."
		)
	)

class Source(models.Model):
	# this is just temporary, saving more complicated stuff for later
	year = models.IntegerField("Year of Publication")
	shortname = models.CharField("Source Short Name", max_length=200) # Just for the UI, so people can identify the source
	identifier = models.CharField("Source Identifier", max_length=1000) # Unique identifiers, placeholder field, think ISBN, or NBN

class Definition(models.Model):
	entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
	pos = models.ForeignKey(PartOfSpeech, on_delete=models.PROTECT)
	definition_text = models.TextField("Definition Text")									# e.g. "booty, plunder, spoils of war"
	source = models.ForeignKey(Source, on_delete=models.PROTECT, null=True, blank=True)		# optional, because some definitions are not sourced	

class UsageExample(models.Model):
	definition = models.ForeignKey(Definition, on_delete=models.CASCADE) 
	persoarabic = models.TextField("Usage Example in Perso-Arabic")
	latin_strict = models.TextField("Usage Example in Verbatim Latin")
	gloss = models.TextField("English Gloss of Usage Example", blank=True)
	source = models.ForeignKey(Source, on_delete=models.PROTECT)

class Etymology(models.Model):
	# possibly implement sequence to record chronology
	entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
	language = models.ForeignKey(Language, on_delete=models.PROTECT)	# e.g. from Arabic
	word = models.CharField("Source Word", max_length=500)				# e.g. غَنِيمَة

